### ISSUE TITLE
Dangling party pointer on Character. Race condition? (was: Crash POL 09/22 19:20:19)

### ISSUE THREAD

**Issue by nogu3ira** [polserver/polserver#15]
```
sysload=6 (0) cputime=0
Signal "SIGSEGV"(11: invalid memory reference) detected.
Segmentation fault detected - faulty memory reference at location: 0x7f545406d000
Signal code is 2
###### 

POL will exit now. Please, post the following to the forum: http://forums.polserver.com/.
#00 0x00000000949d4756 in >> Pol::Clib::ExceptionParser::getTrace():[0x46] from ./lib/libclib.so
#01 0x00000000949d5c88 in >> Pol::Clib::ExceptionParser::handleExceptionSignal(int):[0x68] from ./lib/libclib.so
#02 0x0000000093f418d0 in :[0xf8d0] from /lib/x86_64-linux-gnu/libpthread.so.0
#03 0x000000000064ec39 in >> Pol::Core::Party::on_stam_changed(Pol::Mobile::Character*) const:[0x139] from ./pol
#04 0x000000000062dd08 in >> Pol::Network::send_uo_stamina(Pol::Network::Client_, Pol::Mobile::Character_, Pol::Core::Vital const*):[0x1c8] from ./pol
#05 0x000000000062d0fd in >> Pol::Network::ClientInterface::tell_vital_changed(Pol::Mobile::Character_, Pol::Core::Vital const_):[0x3d] from ./pol
#06 0x000000000057179c in >> Pol::Mobile::Character::consume(Pol::Core::Vital const*, Pol::Mobile::VitalValue&, unsigned int):[0x3c] from ./pol
#07 0x0000000000579489 in >> Pol::Mobile::Character::move(unsigned char):[0x249] from ./pol
#08 0x00000000005fe200 in >> Pol::Core::handle_walk(Pol::Network::Client_, Pol::Core::PKTIN_02_):[0x40] from ./pol
#09 0x0000000000625a02 in >> Pol::Core::process_data(Pol::Network::Client*):[0x7f2] from ./pol
#10 0x00000000006293ae in >> Pol::Core::client_io_thread(Pol::Network::Client*, bool):[0xf8e] from ./pol
#11 0x00000000949f578f in :[0x4f78f] from ./lib/libclib.so
#12 0x0000000094a0071e in >> Pol::threadhelp::run_thread(void (_)(void_), void*):[0xe] from ./lib/libclib.so
#13 0x0000000094a008e8 in >> Pol::threadhelp::thread_stub2(void*):[0x58] from ./lib/libclib.so
#14 0x0000000093f3a0a4 in :[0x80a4] from /lib/x86_64-linux-gnu/libpthread.so.0
#15 0x0000000092ada87d in clone:[0x6d] from /lib/x86_64-linux-gnu/libc.so.6

Admin contact: anonymous
Executable: ./pol
Start time: [09/02 10:46:07] 
Current time: [09/22 19:20:19] 

Stack trace:
#00 0x00000000949d4756 in >> Pol::Clib::ExceptionParser::getTrace():[0x46] from ./lib/libclib.so
#01 0x00000000949d5c88 in >> Pol::Clib::ExceptionParser::handleExceptionSignal(int):[0x68] from ./lib/libclib.so
#02 0x0000000093f418d0 in :[0xf8d0] from /lib/x86_64-linux-gnu/libpthread.so.0
#03 0x000000000064ec39 in >> Pol::Core::Party::on_stam_changed(Pol::Mobile::Character*) const:[0x139] from ./pol
#04 0x000000000062dd08 in >> Pol::Network::send_uo_stamina(Pol::Network::Client_, Pol::Mobile::Character_, Pol::Core::Vital const*):[0x1c8] from ./pol
#05 0x000000000062d0fd in >> Pol::Network::ClientInterface::tell_vital_changed(Pol::Mobile::Character_, Pol::Core::Vital const_):[0x3d] from ./pol
#06 0x000000000057179c in >> Pol::Mobile::Character::consume(Pol::Core::Vital const*, Pol::Mobile::VitalValue&, unsigned int):[0x3c] from ./pol
#07 0x0000000000579489 in >> Pol::Mobile::Character::move(unsigned char):[0x249] from ./pol
#08 0x00000000005fe200 in >> Pol::Core::handle_walk(Pol::Network::Client_, Pol::Core::PKTIN_02_):[0x40] from ./pol
#09 0x0000000000625a02 in >> Pol::Core::process_data(Pol::Network::Client*):[0x7f2] from ./pol
#10 0x00000000006293ae in >> Pol::Core::client_io_thread(Pol::Network::Client*, bool):[0xf8e] from ./pol
#11 0x00000000949f578f in :[0x4f78f] from ./lib/libclib.so
#12 0x0000000094a0071e in >> Pol::threadhelp::run_thread(void (_)(void_), void*):[0xe] from ./lib/libclib.so
#13 0x0000000094a008e8 in >> Pol::threadhelp::thread_stub2(void*):[0x58] from ./lib/libclib.so
#14 0x0000000093f3a0a4 in :[0x80a4] from /lib/x86_64-linux-gnu/libpthread.so.0
#15 0x0000000092ada87d in clone:[0x6d] from /lib/x86_64-linux-gnu/libc.so.6

Compiler: gcc 4.9.2
Compile time: 16:42:54
Build target: LINUX (64bit)
Build revision: POL99.0.0 Break Everything Even Rudder
GNU C library (compile time): 2.19
###### 

```

**Comment by frozenblit** [comment]
This is clear on issue #25 and #30.
